version: 0.0
os: linux

files:
  - source: target/demoapp.war
    destination: /home/ec2-user/apache-tomcat-9.0.74/webapps/

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

file_exists_behavior: OVERWRITE    
          
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user 
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
